### ISSUE TITLE
Load QGIS Processing Config to use Script provider

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-wps#2]
The QGIS procesing Script provider https://github.com/qgis/QGIS/tree/master/python/plugins/processing/script can be used to defined algorithms without providing a QGIS plugin.

The scripts for QGIS Processing has been loaded from directories. The default one is in the processing user folder: 
https://github.com/qgis/QGIS/blob/master/python/plugins/processing/script/ScriptUtils.py#L49
```python
def defaultScriptsFolder():
    folder = str(os.path.join(userFolder(), "scripts"))
    mkdir(folder)
    return os.path.abspath(folder)
```
Other folders can be defined through QGIS Processing config
https://github.com/qgis/QGIS/blob/master/python/plugins/processing/script/ScriptUtils.py#L55
```python
def scriptsFolders():
    folder = ProcessingConfig.getSetting(SCRIPTS_FOLDERS)
    if folder is not None:
        return folder.split(";")
    else:
        return [ScriptUtils.defaultScriptsFolder()]
```

userFolder: https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tools/system.py#L41
ProcessingConfig: https://github.com/qgis/QGIS/blob/master/python/plugins/processing/core/ProcessingConfig.py

**Comment by dmarteau** [comment]
Fixed in commit: 8dc670951498f3323a7d4b4671825d4fd1ae4ce8

By default, the scripts folder location is defined at `<QYWPS_PROCESSSING_PROVIDERS_MODULE_PATH>/scripts`.

Another location can be defined with the configuration variable `QYWPS_PROCESSSING_SCRIPT_FOLDERS`. 

In order to publish scripts to the wps interface, you must add  *script* to the list of published providers
(`QYWPS_PROCESSSING_PROVIDERS`)
